Fix quick start example in README
This fixes the error `TypeError: Request.__init__() missing 1 required positional argument: 'scope'` descrived in the issue

https://github.com/taskiq-python/taskiq-fastapi/issues/18